services:
  db:
    image: postgres
    restart: always
    container_name: personal-finance-tracker-postgres
    environment:
      - POSTGRES_PASSWORD=personal-finance-tracker
      - POSTGRES_USER=personal-finance-tracker
      - POSTGRES_DB=personal-finance-tracker
    volumes:
      - ./infra/postgres/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: personal-finance-tracker-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@personal-finance-tracker.app
      - PGADMIN_DEFAULT_PASSWORD=personal-finance-tracker
    ports:
      - '5050:80'
    depends_on:
      - db
    volumes:
      - ./infra/pgAdmin/servers.json:/pgadmin4/servers.json
      - ./infra/pgAdmin/pgpass:/pgpass
  redis:
    image: redis/redis-stack:latest
    restart: always
    container_name: personal-finance-tracker-redis
    ports:
      - 6379:6379
      - 8001:8001
  minio:
    image: quay.io/minio/minio:latest
    container_name: personal-finance-tracker-minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './infra/minio:/data'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=personal-finance-trackerpass
    command: server --console-address ":9001" start
    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 5s
      timeout: 5s
      retries: 5

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=personal-finance-trackerpass
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add personal-finance-tracker http://minio:9000 MINIO_ROOT_USER MINIO_ROOT_PASSWORD) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb personal-finance-tracker/files;
      /usr/bin/mc policy set download personal-finance-tracker/files;
      exit 0;
      "
  mailhog:
    image: mailhog/mailhog
    container_name: personal-finance-tracker-mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
