# fly.toml app configuration file generated for lumina-stage-web on 2024-03-26T12:59:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'personal-finance-tracker-client-main'
primary_region = 'waw'

[env]

[build.args]
  ENVIRONMENT = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1