name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  server-main:
    name: Deploy production server-main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -c infra/server-main/fly.toml  --dockerfile infra/server-main/Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  client-main:
    name: Deploy production client-main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -c infra/client-main/fly.toml --dockerfile infra/client-main/Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
